[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-Wl,-application_extension"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,@loader_path"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,@loader_path"] 