// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Supported tensor data types
enum DataType {
  f32,
  f64,
  i32,
  i64,
  u8,
  u32,
  bool,
  ;
}

/// Tensor specification for model inputs/outputs
class TensorSpec {
  /// Tensor name
  final String name;

  /// Expected shape (None for dynamic dimensions)
  final List<BigInt?> shape;

  /// Data type
  final DataType dataType;

  /// Optional description
  final String? description;

  const TensorSpec({
    required this.name,
    required this.shape,
    required this.dataType,
    this.description,
  });

  @override
  int get hashCode =>
      name.hashCode ^ shape.hashCode ^ dataType.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TensorSpec &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          shape == other.shape &&
          dataType == other.dataType &&
          description == other.description;
}
